CREATE DATABASE CALE;

USE CALE;

CREATE TABLE USUARIO(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NOMBRE VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	CONTRASENIA VARCHAR(500) NOT NULL,
	TELEFONO VARCHAR(9),
	DIRECCION VARCHAR(255)
);

CREATE TABLE ANIMAL(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NOMBRE VARCHAR(100) NOT NULL,
	ESPECIE VARCHAR(50) NOT NULL,
	RAZA VARCHAR(50),
	EDAD INT,
	SEXO VARCHAR(20) CHECK(SEXO IN ('MACHO', 'HEMBRA', 'OTRO')) NOT NULL,
	ESTADO VARCHAR(20) DEFAULT 'DISPONIBLE' CHECK(ESTADO IN ('DISPONIBLE', 'ADOPTADO')),
	IMAGE_URL VARCHAR(500),
	DUENO_ID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (DUENO_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE ADOPCION(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	USUARIO_ID UNIQUEIDENTIFIER NOT NULL,
	ANIMAL_ID UNIQUEIDENTIFIER NOT NULL,
	FECHA_ADOPCION DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
	FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID)
);